cities = ['Moscow', 'new york', 'Toronto', 'melburn', 'Sochi']
print(cities)
print(len(cities))
print(cities[3])
print(cities[-1])
print(cities[-1].lower())
print(cities[-1].upper())
print(cities[-2].title())
cities[3] = 'Zjuhyh'
print(cities)
cities.append('St. Peterburg')
print(cities)
cities.insert(1, 'Paris')
print(cities)
del cities[-1]
print(cities)
cities.remove('new york')
print(cities)
deleted_city = cities.pop()
print(cities)
#(cities.sort(reverse=True))
#print(cities)
cities.reverse()
print(cities)
